= Bootstrap Guide
:author: Tony Kay
:revdate: Mar 19, 2018
:revnumber: 1.5
:lang: en
:encoding: UTF-8
:doctype: book
:source-highlighter: coderay
:source-language: clojure
:toc: left
:toclevels: 2
:sectlinks:
:sectanchors:
:leveloffset: 1
:sectnums:
:imagesdir: assets/img
:scriptsdir: js
:imagesoutdir: docs/assets/img

ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

ifdef::env-github[]
toc::[]
endif::[]

= Bootstrap (CSS Wrappers)

Fulcro includes a set of CLJC wrappers for a good portion of Bootstrap 3. These should be considered of alpha quality,
but they are used in many demos and can be useful in getting started quickly. The primary improvements that are
needed would be easy contributions, and if you find them useful you can send a pull request to fix issues or
extend them.

NOTE: You must include version 3 of Bootstrap's CSS (and optionally theme), but *not* Javascript, in your HTML file.

The CSS affects many DOM elements, which means you'll see examples that use DOM functions, which
in turn require a JavaScript object as the first argument (for performance). The helper functions from the
`bootstrap` namespace need to modify the incoming arguments, so the first argument (if it takes DOM props) is
a cljs map instead.

```
; render a regular DOM element:
(dom/div #js { :className "a" })
; render a bootstrap element via one of these functions
(b/button { :className "b"} "Button label")
```

The javascript object verion with regular DOM elements avoid data conversion overhead at runtime. The bootstrap functions
in this library need to augment and manipulate the passed parameters, so they use cljs maps instead.

This documentation covers the passive elements that largely add in proper structure and classnames for bootstrap rendering. The
other sections on bootstrap cover active elements.

Fulcro also includes `fulcro.ui.html-entities` (which we alias to `ent` here). These just give symbol names
to HTML entities (e.g. `&times;` is `ent/times`) so they are easier to use in React.

The examples in this section all render within iframes to prevent the bootstrap CSS from interfering with
the book itself. Some of them intentionally go beyond their normal borders to show how they work on larger screens (even
though your screen might not be that large).

== Grids

The four iframes below represent the widths of a large, medium, small, and xsmall screen. The content being
rendered is:

```
(b/container-fluid {}
  (b/row {}
    (b/col {:xs 12 :md 8} "xs 12 md 8") (b/col {:xs 6 :md 4} "xs 6 md 4"))
  (b/row {}
    (b/col {:xs 6 :md 4} "xs 6 md 4")
    (b/col {:xs 6 :md 4} "xs 6 md 4")
    (b/col {:xs 6 :md 4} "xs 6 md 4"))
  (b/row {} (b/col {:xs 6 } "xs 6") (b/col {:xs 6 } "xs 6")))
```

See the Bootstrap documetation for more details.

++++
<div class="example" id="bootstrap-grid"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-grid').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-grid source"]
----
include::src/book/book/bootstrap/grid.cljs[]
----

== Typography

Various elements support modified typography.

++++
<div class="example" id="bootstrap-typography"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-typography').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-typography source"]
----
include::src/book/book/bootstrap/typography.cljs[]
----

== Formatting Code

++++
<div class="example" id="bootstrap-code"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-code').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-code source"]
----
include::src/book/book/bootstrap/code.cljs[]
----

== Tables

++++
<div class="example" id="bootstrap-tables"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-tables').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-tables source"]
----
include::src/book/book/bootstrap/tables.cljs[]
----

== Alerts

++++
<div class="example" id="bootstrap-alerts"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-alerts').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-alerts source"]
----
include::src/book/book/bootstrap/alerts.cljs[]
----

== Badges

An inline badge that can be placed on other elements.

++++
<div class="example" id="bootstrap-badges"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-badges').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-badges source"]
----
include::src/book/book/bootstrap/badges.cljs[]
----

== Breadcrumbs

++++
<div class="example" id="bootstrap-breadcrumbs"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-breadcrumbs').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-breadcrumbs source"]
----
include::src/book/book/bootstrap/breadcrumbs.cljs[]
----

== Buttons

++++
<div class="example" id="bootstrap-buttons"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-buttons').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-buttons source"]
----
include::src/book/book/bootstrap/buttons.cljs[]
----

== Button Groups

++++
<div class="example" id="bootstrap-button-groups"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-button-groups').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-button-groups source"]
----
include::src/book/book/bootstrap/button_groups.cljs[]
----

== Form Fields

++++
<div class="example" id="bootstrap-form-fields"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-form-fields').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-form-fields source"]
----
include::src/book/book/bootstrap/form_fields.cljs[]
----

== Icons

Glyphicon support through keyword names and the `b/glyphicon` function.
E.g. `(b/glyphicon {} :arrow-left)`.

++++
<div class="example" id="bootstrap-icons"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-icons').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-icons source"]
----
include::src/book/book/bootstrap/icons.cljs[]
----

== Images

++++
<div class="example" id="bootstrap-images"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-images').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-images source"]
----
include::src/book/book/bootstrap/images.cljs[]
----

== Jumbotron

A container that offsets the content. Note, this will not work if it isn't in the grid:

++++
<div class="example" id="bootstrap-jumbotron"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-jumbotron').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-jumbotron source"]
----
include::src/book/book/bootstrap/jumbotron.cljs[]
----

== Pagination

++++
<div class="example" id="bootstrap-pagination"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-pagination').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-pagination source"]
----
include::src/book/book/bootstrap/pagination.cljs[]
----

== Panels

Panels use sub-elements to identify portions of the panel:

```
  (b/panel nil
    (b/panel-heading nil "Heading without title")
    (b/panel-body nil "This is the body of the panel")
    (b/panel-footer nil "The footer"))
  (b/panel {:kind :danger}
    (b/panel-heading nil
      (b/panel-title nil "Panel Title of :danger panel"))
    (b/panel-body nil "This is the body of the panel"))))
```

NOTE: Tables can replace or follow the `panel-body`. They need not be placed within it.

```
(b/panel nil
  (b/panel-heading nil
    (b/panel-title nil "Panel with a table and no panel-body"))
  (b/table nil
    (dom/tbody nil
      (dom/tr  nil
        (dom/th nil "Name")
        (dom/th nil "Address")
        (dom/th nil "Phone"))
      (dom/tr  nil
        (dom/td nil "Sally")
        (dom/td nil "555 N Nowhere")
        (dom/td nil "555-1212")))))
```

++++
<div class="example" id="bootstrap-panels"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-panels').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-panels source"]
----
include::src/book/book/bootstrap/panels.cljs[]
----

== Popovers

Popovers are real React components (instead of just wrapper functions), thus the factory has a ui prefix.
They do not have state, so they are fed their orientation and current state via props. You can include a
single child (tree), and the popover will use that as its boundary for locating itself.

(Only the Toggle All is hooked up in this example)

++++
<div class="example" id="bootstrap-popover"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-popover').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-popover source"]
----
include::src/book/book/bootstrap/popover.cljs[]
----

== Progress Bars

++++
<div class="example" id="bootstrap-progress"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-progress').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-progress source"]
----
include::src/book/book/bootstrap/progress.cljs[]
----

== Thumbnails

++++
<div class="example" id="bootstrap-thumbnails"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-thumbnails').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-thumbnails source"]
----
include::src/book/book/bootstrap/thumbnails.cljs[]
----

== Wells

++++
<div class="example" id="bootstrap-well"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-well').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-well source"]
----
include::src/book/book/bootstrap/well.cljs[]
----

= Bootstrap (Components)

This chapter covers Fulcro implementations of some of the Bootstrap components. These have been re-implemented in
CLJC to support server-side rendering and easy inclusion in your Fulcro applications without having to depend on
external Javascript.

These components therefore define mutations that manipulate them, and must be composed in with queries and
such.

== Collapse

The collapse item is a stateful component that takes children. The children will be hidden/shown based on the
state of the collapse wrapper.

The built-in mutation `(b/toggle-collapse {:id ID-OF-COLLAPSE})` can be used to toggle a specific item, and
the mutation `(b/set-collapse {:id ID :open BOOLEAN})` can be used to set the specific state.

NOTE: Both of these mutations automatically do nothing if an animation is in progress.

An example with source is below:

++++
<div class="example" id="bootstrap-collapse"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-collapse').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-collapse source"]
----
include::src/book/book/bootstrap/components/collapse.cljs[]
----

== Accordian (group of collapse)

There is no default coordination among collapse items, but they have a well-known table in app state. Therefore it
is easy to provide a way to group them together into an accordian. The behavior is implemented with a single
additional mutation:

```
(b/toggle-collapse-group-item {:item-id ID :all-item-ids IDs)
```

This mutation toggles the specific item (by ID), and it understands the grouping because you also pass it
the IDs of all of the other items in the group. There's no real need for them to be any
more tightly coupled.

For example, say we choose to use a `panel-group` to lay out each item. Each item can be a
panel, so we define an extra `accordian-section` function (not part of the library) and
create the instances in app state and map over them with our helper.

Note that you can use the mutations defined for single Collapse elements (of course), but that will cause
strangeness in your accordian (e.g. two sections open at once). The `toggle-collapse-group-item` *does*
this correctly by closing all open sections except the one being opened.

++++
<div class="example" id="bootstrap-accordian"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-accordian').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-accordian source"]
----
include::src/book/book/bootstrap/components/accordian.cljs[]
----

== Dropdowns

Active dropdowns are components with state. They must be initialized in app state, and have simple
data constructor functions you can use for this purpose:

* `dropdown` : a function that creates a dropdown's state
* `dropdown-item` : a function that creates an items with a label
* `ui-dropdown` : renders the dropdown. It requires the dropdown's properties, and allows optional named arguments
** `:onSelect` : The callback for selection which receives an element's ID.
** `:kind` : Identical to the `button` `:kind` attribute.

All labels are run through `tr-unsafe`, so if a translation for the current locale exists it will be used.

The following mutations are are available:

Close (or open) a specific dropdown by ID:

```
(prim/transact! component `[(b/set-dropdown-open {:id :dropdown :open? false})]`)
```

Close dropdowns (globally). Useful for capturing clicks a the root to close dropdowns when the user clicks outside of
an open dropdown.

```
(prim/transact! component `[(b/close-all-dropdowns {})])
```

You can set highlighting on an item in the menu (to mark it as active) with:

```
(prim/transact! component `[(b/set-dropdown-item-active {:id :item-id :active? true})])
```

++++
<div class="example" id="bootstrap-dropdowns"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-dropdowns').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-dropdowns source"]
----
include::src/book/book/bootstrap/components/dropdowns.cljs[]
----

== Modals

Modals are stateful Fulcro components with app state and queries. They can, of course, be mixed with other
app state.

The basic usage is to define your modal in the root, with the various things it should render. If you need
more than one kind of modal, then you can use a UI router and embed them all in it, then embed the router
at the root.

The following demonstrates all of these techniques:

++++
<div class="example" id="bootstrap-modals"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-modals').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-modals source"]
----
include::src/book/book/bootstrap/components/modals.cljs[]
----

== Modal Variations

This section just demonstrates some non-active modals so you can see some of the different layout sizes and options.

NOTE: The iframe for some examples are forced larger than the container because large modals adapt down in size based on
available space.

++++
<div class="example" id="bootstrap-modal-variations"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-modal-variations').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-modal-variations source"]
----
include::src/book/book/bootstrap/components/modal_variations.cljs[]
----

== Nav

These are stateful components that act as tabs. A nav contains one or more `nav-link` or `dropdown`. It reports selections
through an `onSelect` callback (which will send the ID of the item selected).

The typical way to embed a nav is using the `nav` constructor in your initial state, adding `Nav`'s query to the query at
the same key, and rendering it with `ui-nav`.

In the demo below we define this mutation to call from the onSelect callback to display where the nav is currently
pointing:

```clojure
(m/defmutation nav-to [{:keys [page]}]
  (action [{:keys [state]}] (swap! state assoc :current-page page)))
```

Then the main component can display nav and also show the current 'page'.

++++
<div class="example" id="bootstrap-nav"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-nav').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-nav source"]
----
include::src/book/book/bootstrap/components/nav.cljs[]
----

== Nav and UI Routing

The Nav component does nothing more than manage the UI of the tabs. You are still responsible for rendering the
content of the application. You will likely wish to use the Fulcro routing system so that your UI performance stays
high, and HTML5 routing becomes simpler. To this end, you will likely want to combine Nav with routing.

=== Defining the UI Routing

First, we'll need some screens to show. We'll just make some placeholders. They'll need to know (and query) their
screen type:

Then we'll need to define an ident that follows the `[type id]` semantic. Since there isn't really an ID, we'll just
use the keyword `:singleton` for the ID.

```clojure
(ident [this props] [(:screen-type props) :singleton])
```

but this ident function goes with the UI router, which looks like this:

```clojure
(defrouter MainRouter :main-router
  (ident [this props] [(:screen-type props) :singleton])
  :home HomeScreen
  :other OtherScreen)
```

=== Composing the UI Elements

Composing the UI requires that you query for the correct router and nav subelements, compose in their initial state,
and render them both. Something like this will work:

=== Changing the Visible Screen

This is now a component that can display whichever screen is currently active. The `fulcro.client.routing` namespace
includes a helper functions called `set-route*` that can be composed into a mutation to change the current screen of
a router:

```
(m/defmutation select-tab
  "Select the given tab"
  [{:keys [tab]}]
  (action [{:keys [state]}]
    (swap! state routing/set-route* :main-router [tab :singleton])))
```

Of course, we could also be using the routing tree mechanisms, which would be similar (though you'd use the
`update-routing-links` helper then).

=== Ensuring the Correct Tab is Active

If you're using something like HTML5 routing, then you'll not only need to make sure the current screen is showing,
but you'll need to make sure the `Nav` knows which tab to show as active. The bootstrap namespace includes
an mutation for setting the current nav link `set-active-nav-link`, and a helper function `set-active-nav-link*`
that can be composed into mutations.

If you're careful to make the IDs of the tabs and screens the same, then you'll be able to ensure lock-step
updates with that same mutation:

```clojure
(m/defmutation select-tab
  "Select the given tab"
  [{:keys [tab]}]
  (action [{:keys [state]}]
    (swap! state (fn [s]
                   (-> s
                     (routing/set-route* :main-router [tab :singleton])
                     (b/set-active-nav-link* :main-nav tab))))))
```

The overall technique works the same with routing trees, but in that case you'll need to know what nav links need
to be updated for a given page and compose those instructions with the `routing/update-routing-links` helper.

++++
<div class="example" id="bootstrap-nav-routing"> </div>
<a class="source-toggle" href="javascript:void(0)" onClick="$('.bootstrap-nav-routing').toggle()">Show/Hide Source</a>
++++

[source,clojure,role="bootstrap-nav-routing source"]
----
include::src/book/book/bootstrap/components/nav_routing.cljs[]
----

