== Porting From Fulcro 2.x

Fulcro 3 is intended to be as API-friendly to Fulcro 2 applications as
possible but internal cleanup and changes mean that existing applications will
have to at least make some name changes, and in many cases clean
up arguments and logic. This document covers the known porting
tasks. If you run into an issue when porting that is not documented
here please ask on the Fulcro Slack channel in Clojurians.

=== Idents are Refs (UNDER CONSIDERATION)

One central theme of Fulcro from the very beginning is component-based
database normalization.  The term `ident` was used by the original Om Next
project from which Fulcro claims its roots.  Over time it has become apparent that
the term "ident", which Cognitect uses in Clojure to mean "a keyword or symbol"
(`ident?` was added to core in 1.9), is a somewhat poor choice for the name.

The real origin of the concept came from Datomic's Lookup Refs, which name
a "unique identity" attribute and the value of that attribute as a vector (e.g.
`[:account/id 33]`).

Thus the larger Clojure community generally recognizes these kinds of vectors as
"lookup refs".

NOTE: As a curious historical note: there were early debates as to what to call
these things, both `ref` and `ident` were in use in Om Next's early code, and "ident" won;
however, some things like mutation `env` were missed and have always had a `:ref` member.

Since we're renaming a bunch of stuff already: Fulcro 3 may adopt "lookup ref" or "ref"
as the new official terminology in its function and parameter naming.

One problem is that `ref` is another already claimed "thing", and `:lookup-ref` is
a bit cumbersome to type.

=== Namespaces and Name Changes

Since the API changed, we thought it a good opportunity to clean
up some naming and split things into smaller files. This will help
with long-term maintenance of the project.

If you look at the `com.fulcrologic.fulco` package you should be able
to guess the location of the function you need. There are some functions
that were moved out of Fulcro completely or were dropped because they
were deprecated or no longer made sense.

The following list documents some common ones that you might be using, 
and where to find them now:

`ident?`:: Most EQL-related functions like this are in the
    `edn-query-language.core` namespace.

`merge-*`:: Merge-related logic is now in the
`com.fulcrologic.fulcro.algorithms.merge` namespace.


=== API Improvements that Should Not Hurt

Default query transform:: When issuing loads the new code elides `:ui/...` keywords
*and also* the form-state config join.

Rendering:: The default renderer no longer needs "follow-on reads".  Performance
testing showed that the process of trying to figure out UI updates from the indexes
added more overhead than they saved.  The rendering optimizations are actually pluggable,
and two versions of the algorithm are supplied: one that always renders from root
(`keyframe-render`) and relies on `shouldComponentUpdate` for performance,
and one that uses database analysis to find the minimum number of components to update.
Different applications might find one better than the other depending on usage patterns.
Both should be faster than Fulcro 2 for various internal reasons.  Until heavy use proves otherwise
The "keyframe" one is more likely to be bug-free.  There is some chance that I'll support
follow-on reads as a fallback to the 2.x meaning (when they are present on a tx). In general the majority
of the overhead at this point is in React, so relying on Fulcro 3 to calculate what to refresh is not likely to
be your bottleneck.

Pessimistic Transactions:: These were always a bit of a "hard edge" in Fulcro 2.  In the JS world the ability to
"chain" operations in callbacks with async/await is just sometimes desirable. Fulcro 3 allows this sort of thing
more directly (though it still keeps it
out of the UI layer). The new mutation abilities allow you to chain your next operation from the network
result of a prior one right in the mutation's declaration.  `ptransact!` is technically still supported, and
actually should even have a bug or two fixed, but should probably not be used in new applications.

Transactions:: The new transact API uses a proper submission queue. This gets rid of internal uses of core async,
makes the internals more visible to APIs and tooling, and even allows for the entire transaction processing system
to be "pluggable".  The new system allows `transact!` to be safely called from anywhere. Semantically speaking it
should not be called from within `swap!`, though in js (single-threaded) even *that* would not hurt anything
with the new implementation.

`defmutation`:: The `defmutation` macro on the client side "looks" the same as the old one; however, it is quite a bit
more powerful.  Lessons learned in incubator and with pessimistic mutations led to a complete redesign.  Dumping the
internal structure of Om Next simplified the whole process greatly.  The backing `defmulti` is still there, but the arguments
changed (it takes only and env now), and you are guaranteed that the built-in tx processing will only ever call the
method *once*.  Remotes are now truly lambdas (instead of values), and receive an env that allows them to see app state
as it existed before the optimistic update.

=== Breaking API Changes

React Lifecycle Methods:: The *non-static* React lifecycle methods (e.g. componentDidMount, shouldComponentUpdate, etc.) now all require
an explicit `this`. Everything in the options map in Fulcro 3 except query/ident/initial-state are completely literal
(e.g. lambdas or data).

Mutation Multimethod:: The `defmulti` for mutations is still present, but the API is presents and the return value
it expects have changed.  If you directly use `defmethod m/mutate` you will need to adapt your code.

Initial State:: The initial state story is the same if your initial state is purely on your root component. If
you were passing an initial state to the reconciler, then that option has changed.  You can pass a *normalized* database
to `fulcro-app`, and you can turn on/off auto inclusion of initial state from root via `mount!`.

App vs. Reconciler:: There is no longer a separate reconciler or indexer.  Everything
is in the app, and is held in atoms such that there is no need to do top-level swaps. Your
app can be declared once in a namespace of it's own and then used directly everywhere
the reconciler could have been. There are no protocols involved.

Returning and Targeting:: The `returning`, `with-target`, and `with-params` helpers take `env` now.  The return value
of client-side mutations now support returning the `env` in addition to the original boolean or AST.

Remotes:: Remotes were protocol based, and are now simply maps. The primary
"method" to implement is a function under the `:transmit!` key, which now receives
a send node and should return a result that includes both the status code and EDN
result.  There are new versions of pre-supplied HTTP and Websocket remotes that
should be top-level API compatible with your existing code.

Server:: Easy server is gone. Supported server middleware helpers and config support
are in the `com.fulcrologic.fulcro.server` package. Fulcro 3 no longer supplies
server-side macros for mutations and reads, as `pathom` is a much better choice for
EQL service.

UI State Machines:: The names of a few parameters on API for
doing loads and mutations were named. The load `::uism/post-event` was
renamed to `::uism/ok-event`, fallbacks to error, etc.  The targeting
namespace on the target for mutations was change to data-targeting, and
the namespace for returning was change to normal mutations ns.

