# Untangled for Om Next
:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

Untangled is a library stacked on Om Next that provides much of what is needed to use that library (client parser,
networking, server elements, a database format, clear constructs for data loading). The intention is to provide you
with most of the experience of Om Next with very little of the pain.

## Writing Applications with Untangled

image::https://img.shields.io/clojars/v/awkay/untangled.svg[link=https://clojars.org/awkay/untangled]

Release: image:https://api.travis-ci.org/awkay/untangled.svg?branch=master[link=https://github.com/awkay/untangled/tree/master]
Snapshot: image:https://api.travis-ci.org/awkay/untangled.svg?branch=develop[link=https://github.com/awkay/untangled/tree/develop]


See link:/GettingStarted.adoc[GettingStarted.adoc] to get going.

Once you've got the general idea, there's more info in the developers guide, which is an interactive
guide where you edit the code as you go. To use the developers guide, clone this repository and run:

```
./run-devguide.sh
```

and follow the instructions.

## See Some Demos

There are a number of demos that show how particular common things are done with Untangled. To view them use
the `run-demos.sh` shell script at the top of this project and follow the instructions it gives.

This compiles the demos, and runs a server that can respond to the full-stack examples.

NOTE: A number of things might use the network port of the demo server, so don't try to do this while also
doing something else in the project.
