:source-highlighter: coderay
:source-language: clojure
:toc:
:toc-placement: preamble
:sectlinks:
:sectanchors:
:sectnums:

# Untangled for Om Next

image::https://img.shields.io/clojars/v/awkay/untangled.svg[link=https://clojars.org/awkay/untangled]

Release: image:https://api.travis-ci.org/awkay/untangled.svg?branch=master[link=https://github.com/awkay/untangled/tree/master]
Snapshot: image:https://api.travis-ci.org/awkay/untangled.svg?branch=develop[link=https://github.com/awkay/untangled/tree/develop]

Untangled is a library stacked on Om Next that provides much of what is needed to use that library (client parser,
networking, server elements, a database format, clear constructs for data loading). The intention is to provide you
with most of the experience of Om Next with very little of the pain.

## Writing Applications with Untangled

The https://awkay.github.io/untangled[website] is a great place to read about
Untangled. It has pages describing things in more general terms, and has links
to various resources like videos and evaluation guides.

If you want to jump and code, read on!

### Getting Started

See link:/GettingStarted.adoc[GettingStarted.adoc] to get going. It covers all of the
basics related to full-stack development in Untangled.

If you don't know Clojure, you should at least get comfortable with the basics.
I recommend: http://www.braveclojure.com/[Clojure for the Brave and True], and doing at least the
basic online exercises at http://www.4clojure.com/[4Clojure]. You should also have
a passing familiarity with Facebook's React, though if you understand that we're
using it to get "fast UI updates", that is sufficient to start.

### Developer's Guide

The Developer's Guide is really an interactive coding tutorial using Devcards. You
can view an http://awkay.github.io/untangled/guide.html[online version],
but in order to use it properly you should clone Untangled and:

```
./run-devguide.sh
```

and follow the instructions.

## See Some Demos

There are a number of demos that show how particular common things are done with Untangled. To view them use
the `run-demos.sh` shell script at the top of this project and follow the instructions it gives.

This compiles the demos, and runs a server that can respond to the full-stack examples.

NOTE: A number of things might use the network port of the demo server, so don't try to do this while also
doing something else in the project.
