(ns app.i18n.de (:require untangled.i18n) (:import goog.module.ModuleManager))

;; This file was generated by untangled's i18n leiningen plugin.

(def
 translations
 {"|This is a test" "Das is ein test",
  "|Hi, {name}" "Hallo, {name}",
  "|N: {n, number} ({m, date, long})"
  "N: {n, number} ({m, date, long})"})

(swap!
 untangled.i18n/*loaded-translations*
 (fn [x] (assoc x "de" translations)))

(try
 (-> goog.module.ModuleManager .getInstance (.setLoaded "de"))
 (catch js/Object e))