(ns app.i18n.en (:require untangled.i18n) (:import goog.module.ModuleManager))

;; This file was generated by untangled's i18n leiningen plugin.

(def translations {})

(swap!
 untangled.i18n/*loaded-translations*
 (fn [x] (assoc x "en" translations)))

(try
 (-> goog.module.ModuleManager .getInstance (.setLoaded locale))
 (catch js/Object e))