(ns app.i18n.en (:require fulcro.i18n) (:import goog.module.ModuleManager))

;; This file was generated by fulcro's i18n leiningen plugin.

(def translations {})

(swap!
 fulcro.i18n/*loaded-translations*
 (fn [x] (assoc x "en" translations)))

(try
 (-> goog.module.ModuleManager .getInstance (.setLoaded "en"))
 (catch js/Object e))