(ns app.i18n.en-US (:require fulcro.i18n) (:import goog.module.ModuleManager))

;; This file was generated by fulcro's i18n leiningen plugin.

(def translations {})

(swap!
 fulcro.i18n/*loaded-translations*
 (fn [x] (assoc x "en-US" translations)))

(if
 (exists? js/i18nDevMode)
 :noop
 (-> goog.module.ModuleManager .getInstance (.setLoaded "en-US")))