(ns app.i18n.es (:require fulcro.i18n) (:import goog.module.ModuleManager))

;; This file was generated by fulcro's i18n leiningen plugin.

(def
 translations
 {"|This is a test" "Spanish",
  "|Hi, {name}" "Ola, {name}",
  "|N: {n, number} ({m, date, long})"
  "N: {n, number} ({m, date, long})"})

(swap! fulcro.i18n/*loaded-translations* assoc "es" translations)

(try
 (-> goog.module.ModuleManager .getInstance (.setLoaded "es"))
 (catch js/Object e))