(ns translations.de (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def
 translations
 {"|Locale Tests. Current locale: "
  "Gebietsschema-Tests. Aktuelle Gebietsschema:",
  "|This is a test." "Das is ein test"})

(swap! fulcro.i18n/*loaded-translations* assoc "de" translations)

#?(:cljs (cljs.loader/set-loaded! :de))