(ns translations.es-MX (:require fulcro.i18n #?(:cljs cljs.loader)))

;; This file was generated by Fulcro.

(def
 translations
 {"|Locale Tests. Current locale: "
  "Pruebas de configuración regional. Localidad actual:",
  "|This is a test." "Esto es un test."})

(swap! fulcro.i18n/*loaded-translations* assoc "es-MX" translations)

#?(:cljs (cljs.loader/set-loaded! :es-MX))